### ISSUE TITLE
Package DATA 606

### ISSUE THREAD

**Issue by MDcontributor** [jbryer/DATA606Spring2017#1]
Hello,

I seem to be having issues loading the DATA606's startLab function. 

I had performed an install.packages("DATA606"), in addition, to all of the other supporting packages necessary as listed in the announcement. However, when I enter this:

startLab('Lab0')

I get an "Error in find.package("IS606") : there is no package called ‘IS606’". I was wondering if this was an error on my part or if the package is indeed truly missing.

Thanks!

- Joel

**Comment by john-grando** [comment]
Joel,

I've been having that issue as well (i'm also a student in the class).  However, I was able to source the Lab data directly from openintro.org.  It seems to be the same information so you can possibly get started while this issue is getting handled.  I just want to warn you that i'm not 100% sure it's the same data, but it looked right when I did my Lab.  Thanks.


`#Source baptism count data`
`source("http://www.openintro.org/stat/data/arbuthnot.R")`
`#Source present day data`
`source("http://www.openintro.org/stat/data/present.R")`

**Comment by MDcontributor** [comment]
Hi John,

Thanks for getting back to me. I had spoken to Dr. Bryer about the dataset,
and there was a portion of the code that he had to rewrite. After
re-installing the package, it is now up and working for me.

- Joel

**Comment by john-grando** [comment]
Hi,

When I reinstalled the package, i received the following error.  It looks like there were no labs downloaded because the getLabs() function doesn't seem to return anything.  Is there something else I should do?  FYI, i'm using Linux.

> library(DATA606)

Welcome to CUNY DATA606 Statistics and Probability for Data Analytics 
This package is designed to support this course. The text book used 
is OpenIntro Statistics, 3rd Edition. You can read this by typing 
vignette('os3') or visit www.OpenIntro.org. 
 
The getLabs() function will return a list of the labs available. 
 
The demo(package='DATA606') will list the demos that are available. 

Attaching package: ‘DATA606’

The following object is masked from ‘package:utils’:

    demo

> startLab('Lab0')
Error in startLab("Lab0") : 
  The lab did not copy! Not sure why, ask your instructor.
> getLabs()
character(0)

**Comment by MDcontributor** [comment]
I had ran into this same issue as well. Dr. Bryer had made some corrections to the code to fix this error. You have to literally re-install everything as noted in the announcement section, including the devtools::install_github('jbryer/DATA606'). When you enter the devtools into the console, it will re-install the DATA606 package for you, and it should have the updated version. Let me know if that works out.

**Comment by john-grando** [comment]
The new error turned out to just be an annoying Linux permission issue.  Thanks for the response!

**Comment by jbryer** [comment]
For now, it appears this issue has been solved. You will need to reinstall the package if you installed before Tuesday.

    devtools::install_github('jbryer/DATA606')

Feel free to reopen if you still have an issue.
